### ISSUE TITLE
Why does mt.Vector inherit from vectorlib?

### ISSUE THREAD

**Issue by lua-rocks** [minetest-toolkit/minetest-api-def-common#1]
@AFCMS Explain this line please:

https://github.com/minetest-toolkit/minetest-api-def-common/blob/49ce692fdd7a4facfffb8a31d5a9fe4be5516c17/vector.lua#L6

- What is `vectorlib`?
- Why do we need this extra class?
- Why its named in different format (not `mt.VectorLib`)?

**Comment by AFCMS** [comment]
This is to allow the use of the `:` to call functions.

```lua
local some_vector = vector.new(10, 20, 30)
local copied_vector = some_vector:copy() --instead of vector.copy(some_vector)
```

If you find something better I would be glad to remove this ugly workaround.

And yes, we should rename it to follow the `mt.*` convention.

**Comment by lua-rocks** [comment]
I just removed it and everything works fine:

![image](https://user-images.githubusercontent.com/82697845/216019273-2bce4b4d-29fd-4af2-82ed-a7e3f6615666.png)

**Comment by AFCMS** [comment]
Nice
